#[cfg(feature = "desktop")]
mod desktop;
pub mod engine;
pub mod error;
pub mod fresh_retry;
pub mod http;
pub mod installed_repair;
pub mod manager;
pub mod migration;
pub mod model;
pub mod providers;
pub mod reconcile;
pub mod recovery;
pub mod release;
pub mod repair_database;
pub mod sql_guard;
pub mod store;
pub mod vault;
#[cfg(feature = "desktop")]
pub use desktop::run;
